name: Release Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "version.txt"
  workflow_dispatch:

concurrency:
  group: release-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  execute-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'sgl-project/specforge'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10'


      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          apt-get update && apt-get install -y pandoc parallel retry

      - name: Build documentation
        run: |
          cd docs
          make compile
          make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
